# branches to build
branches:
  only:
    - master
  except:
    - gh-pages

image: Ubuntu1804  # образ для сборки

stack: node 10  # окружение

# build cache to preserve files/folders between builds
cache:
  - node_modules # local npm modules

# scripts that run after cloning repository
install:
  - yarn # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - yarn build   # команда сборки

# to run your custom scripts instead of automatic tests
test_script:
  - yarn run lint && yarn notest

deploy_script: # скрипт развёртывания
environment:
  GH_TOKEN:
    secure: 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

install:
  - git config --global credential.helper store

build_script:
  - npm install
  - npm run build

on_success:
  - git config --global user.email "you@example.com"
  - git config --global user.name "dbelinsky"
  - git add .
  - git commit -m "Auto-deploy updates [skip ci]"
  - git push https://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@github.com/dbelinsky/dom-game.git HEAD:gh-pages --force